golfstore/config/routes.rb
Golfstore::Application.routes.draw do
  get "orderitems/index"

  get "orderitems/show"

  get "orderitems/new"

  get "orderitems/edit"

  	devise_for :users do
	resources :orders
end
	resources :orders do
	resources :orderitems
end
  	

  devise_for :users

  get "cart/index"

  get "site/about"

  get "site/contact"

  get "site/home"

  resources :items
  
  	match '/cart' => 'cart#index'
	match '/cart/:id' => 'cart#add'
	
	match '/about' => 'site#about'
	match '/contact' => 'site#contact'

	
	match '/cart/remove/:id' => 'cart#remove'
	match '/clearCart' => 'cart#clearCart'
	
	match '/checkout' => 'cart#createOrder'

	
	match '/home' => 'site#home'
	
	root :to => 'site#home'

end

golfstore/app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :category, :description, :image_url, :price, :title
end

golfstore/app/models/order.rb
class Order < ActiveRecord::Base
	attr_accessible :order_date, :user_id
	has_many :orderitems
	belongs_to :user
end

golfstore/app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  attr_accessible :description, :item_id, :price, :quantity, :title
end

golfstore/app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable
	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :remember_me
	has_many :orders
end

golfstore/app/controllers/cart_controller.rb
class CartController < ApplicationController
def add
	id = params[:id]
	cart = session[:cart] ||= {}
	cart[id] = (cart[id] || 0) + 1
	redirect_to :action => :index
end
def index
	@cart = session[:cart] || {}
end
def remove
	id = params[:id]
	cart = session[:cart]
	cart.delete id
	redirect_to :action => :index
end
def clearCart
	session[:cart] = nil
	redirect_to :action => :index
end
def createOrder
# Step 1: Get the current user
@user = User.find(current_user.id)
# Step 2: Create a new order and associate it with the current user
@order = @user.orders.build(:order_date => DateTime.now)
@order.save
# Step 3: For each item in the cart, create a new item on the order!!
@cart = session[:cart] || {} # Get the content of the Cart
@cart.each do | id, quantity |
item = Item.find_by_id(id)
@orderitem = @order.orderitems.build(:item_id => item.id, :title => item.title, :description => item.description, :quantity => quantity, :price => item.price)
@orderitem.save
end
end

def change
cart = session[:cart]
id = params[:id];
quantity = params[:quantity].to_i
if cart and cart[id]
unless quantity <= 0
cart[id] = quantity
else
cart.delete id
end
end
redirect_to :action => :index
end
def checkout
flash[:notice] = "CHECKOUT IS NOT IMPLEMENTED YET!!!"
redirect_to :action => :index
end
end

golfstore/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

golfstore/app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

golfstore/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

golfstore/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

golfstore/app/helpers/cart_helper.rb
module CartHelper
end

golfstore/app/helpers/items_helper.rb
module ItemsHelper
end

golfstore/app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

golfstore/app/helpers/orders_helper.rb
module OrdersHelper
end

golfstore/app/helpers/site_helper.rb
module SiteHelper
end

golfstore/app/views/cart/index.html.erb
<h1>Your Cart</h1>
<% if @cart.empty? %>
<p>Your Cart is empty.</p>
<% end %>
<% total = 0 %>
<table class="cart">
<tr>
<td class="legend"></td>
<td class="legend">Item</td>
<td class="legend">Price</td>
<td class="legend">Qty</td>
<td class="legend">Total</td>
</tr>
<% @cart.each do | id, quantity | %>
<% item = Item.find_by_id(id) %>
<tr>
<td>
<div class="image">
<%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
</div>
</td>
<td class="title"><%= link_to item.title, item %></td>
<td class="price"><%= number_to_currency(item.price) %></td>
<td class="quantity"><%= quantity %><br /></td>
<td class="price">
<%= number_to_currency(quantity * item.price, :unit => "£") %>
</td>
<td><a href="/cart/remove/<%= item.id %>">Remove from Cart</a></td>
</tr>
<% total += quantity * item.price %>
<% end %>
<tr>
<%= link_to 'Clear Cart', :controller => "cart", :action => "clearCart" %>
<%= link_to 'Check Out', :controller => "cart", :action => "createOrder" %>
<td colspan="4">
<div class="total">Total:</div>
</td>
<td>
<div class="price"><%= number_to_currency(total, :unit => "€") %></div>
</td>
</tr>
</table>
<p>
<%= link_to 'Continue Shopping', :controller => :items %>
</p>

golfstore/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

golfstore/app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

golfstore/app/views/items/index.html.erb
<h1>Catalog</h1>
<table class="catalog">
<% @items.each do |item| %>
<tr>
<td>
<div class="image">
<%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
</div>
</td>
<td>
<div class="title">
<%= link_to item.title, item %>
</div>
<div class="description">
<%=h item.description %>
</div>
<div class="price">
<%= number_to_currency(item.price, :unit => "&pound;") %>
</div>
<div class="links">
<%= link_to 'Edit', edit_item_path(item) %> |
<%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %>
<a href="/cart/<%= item.id %>">Add to Cart</a><br><br>
</div>
</td>
</tr>
<% end %>
</table>
<p><%= link_to 'New item', new_item_path %></p>

golfstore/app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

golfstore/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @item.title %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>

<p>
  <b>Image url:</b>
  <%= @item.image_url %>
</p>

<p>
  <b>Category:</b>
  <%= @item.category %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

golfstore/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Online Movie Store</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>
<body>
<div id="wrapper">
  <div id="inner">
    <div id="header">
      <h1><img src="/assets/logo.gif" width="519" height="63" alt="Online Movie Store" /></h1>
      <div id="nav"> <a href="http://all-free-download.com/free-website-templates/">Home</a> | 
      	<a href="http://all-free-download.com/free-website-templates/">View Cart</a> | 
      	<a href="http://all-free-download.com/free-website-templates/">Sign In</a> |
      	<a href="http://all-free-download.com/free-website-templates/">Sign Up</a> 
      	</div>
      <!-- end nav -->
      <a href="http://all-free-download.com/free-website-templates/"><img src="/assets/header_1.jpg" width="744" height="145" alt="Harry Potter cd" /></a> <a href="http://all-free-download.com/free-website-templates/"><img src="/assets/header_2.jpg" width="745" height="48" alt="" /></a> </div>
    <!-- end header -->
    <dl id="browse">
      <dt>Full Category Lists</dt>
      <dd class="first"><a href="http://all-free-download.com/free-website-templates/">Sports</a></dd>
      <dd><a href="http://all-free-download.com/free-website-templates/">Music</a></dd>
      <dd><a href="http://all-free-download.com/free-website-templates/">Theatre</a></dd>
      <dd><a href="http://all-free-download.com/free-website-templates/">Family</a></dd>
      <dd><a href="http://all-free-download.com/free-website-templates/">Last Minute Left-overs</a></dd>
      <dd class="last"><a href="http://all-free-download.com/free-website-templates/">Special Events</a></dd>
      <dt>Search for Your Next Event</dt>
      <dd class="searchform">
        <form action="http://all-free-download.com/free-website-templates/" method="get">
          <div>
            <select name="cat">
              <option value="-" selected="selected">Select your event</option>
              <option value="-">Sports</option>
              <option value="-">Music</option>
              <option value="-">Theatre</option>
              <option value="-">Family</option>
              
            </select>
          </div>
          <div>
            <input name="q" type="text" value="Search Events" class="text" />
          </div>
          <div class="softright">
            <input type="image" src="/assets/btn_search.gif" />
          </div>
        </form>
      </dd>
    </dl>
    <div id="body">
    <p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

     <%= yield %>
     
     <% if user_signed_in? %>
	<div>Signed in as... <%= current_user.email %> (<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>)</div>
	<% else %>
	<%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
	<% end %>
    
    </div>
    <!-- end body -->
    <div class="clear"></div>
    <div id="footer"> Web design by <a href="http://www.freewebsitetemplates.com">free website templates</a> &nbsp;
      <div id="footnav"> <a href="http://all-free-download.com/free-website-templates/">Legal</a> | <a href="http://all-free-download.com/free-website-templates/">Home</a> </div>
      <!-- end footnav -->
    </div>
    <!-- end footer -->
  </div>
  <!-- end inner -->
</div>
<!-- end wrapper -->
<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div></body>
</html>

golfstore/app/views/orderitems/edit.html.erb
<h1>Orderitems#edit</h1>
<p>Find me in app/views/orderitems/edit.html.erb</p>

golfstore/app/views/orderitems/index.html.erb
<h1>Orderitems#index</h1>
<p>Find me in app/views/orderitems/index.html.erb</p>

golfstore/app/views/orderitems/new.html.erb
<h1>Orderitems#new</h1>
<p>Find me in app/views/orderitems/new.html.erb</p>

golfstore/app/views/orderitems/show.html.erb
<h1>Orderitems#show</h1>
<p>Find me in app/views/orderitems/show.html.erb</p>

golfstore/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_date %><br />
    <%= f.datetime_select :order_date %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

golfstore/app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

golfstore/app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Order date</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.order_date %></td>
    <td><%= order.user %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

golfstore/app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

golfstore/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order date:</b>
  <%= @order.order_date %>
</p>

<p>
  <b>User:</b>
  <%= @order.user %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

golfstore/app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

golfstore/app/views/site/contact.html.erb
<h1>Site#contact</h1>
<p>Find me in app/views/site/contact.html.erb</p>

golfstore/app/views/site/home.html.erb
<h1>Site#home</h1>
<p>Find me in app/views/site/home.html.erb</p>